import Head from "next/head";

import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jackey Yang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>

      <Nav />
      <Hero />
      <Projects />
      <Footer />
    </>
  );
}
