import Head from "next/head";

import Nav from "../components/Nav";
import Hero from "../components/Hero";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Jackey Yang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Hero />
      <Projects />
      <div className="h-screen w-11/12"></div>
    </>
  );
}
